from crewai import Agent,Crew, Process, Task
from dotenv import load_dotenv
from crewai import Task
from crewai.llm import LLM
import os
import warnings
from email_fetcher_tool import *
from draft_generator_tool import *



# Ignore all warnings
warnings.filterwarnings("ignore")

# Use CrewAI's LLM wrapper with proper LiteLLM format
from crewai.llm import LLM
load_dotenv()  
llm = LLM(
    model="gemini/gemini-1.5-flash",  
    api_key=os.getenv("GEMINI_API_KEY"),
    temperature=0.5
)
email_fetcher = Agent(
    role="Email Fetcher",
    goal="Fetch unread email threads from Gmail and extract relevant data for processing.",
    verbose=True,
    memory=False,
    backstory=(
        "You are a  email fetcher researcher and pass those fetched emails with id, history, subject."         
    ),
    llm=llm,
    tools=[GmailUnreadThreadsTool()],
    allow_delegation=False
)
response_generator = Agent(
    role="Response Generator",
    goal="You have to generate the response for the email threads given by the email fetcher.",
    verbose=True,
    memory=False,
    backstory=(
        "You are a helpful assistant that generates responses to email threads."          
    ),
    llm=llm,
    allow_delegation=False
)
draft_generator = Agent(
    role="Draft Generator",
    goal="You have to generate the draft email threads which will be given to you by the Response Generator.",
    verbose=True,
    memory=False,
    backstory=(
        "You are a helpful assistant that generates draft email threads."          
    ),
    llm=llm,
    tools=[GmailCreateDraftsFromResponsesTool()],
    allow_delegation=False
)
email_fetcher_task = Task(  
    description= "Read the unread email from Gmail and extract the subject, sender, and thread ID. "
        "You have to use the gmail_unread_threads_reader tool to fetch the unread emails. "  ,
    expected_output=" A list of dictionaries, where each dict has 'thread_id', 'subject', and 'history' of the unread emails",  
    agent=email_fetcher,   
    tools=[GmailUnreadThreadsTool()],  
) 

response_generator_task = Task(    
    description="Based on the unread email threads provided by the email fetcher, generate appropriate responses for each email thread. For each thread, analyze the subject and conversation history to create a relevant and helpful response.",  
    expected_output="A list of dictionaries, where each dict has 'thread_id' as key and response (generated by you) as value.",    
    agent=response_generator,  
    context=[email_fetcher_task]  
)

draft_generator_task = Task(  
    description= "Responses are given to you by the Response Generator, you have to generate the draft email threads and mark those emails whose reply draft has been generated as read."
    "Use gmail_create_drafts_from_responses tool for generating drafts.",  
    expected_output=" Draft of emails",  
    agent=draft_generator,
    context=[response_generator_task] ,  
    tools=[GmailCreateDraftsFromResponsesTool()],  
) 

crew = Crew(
    agents=[email_fetcher,response_generator, draft_generator],
    tasks=[email_fetcher_task, response_generator_task, draft_generator_task],
    process=Process.sequential,
)
result = crew.kickoff()
print(f"Result: {result}")
